version: '3'
services:
  api:
    environment:
      - ES_HOST
      - ES_PASS
      - ES_USER
    image: docker.pkg.github.com/momothereal/wiki/api:latest
    ports:
      - 8080:8080
  frontend:
    image: docker.pkg.github.com/momothereal/wiki/search-tool:latest
    ports:
      - 8081:80

